CREATE TABLE DIRECCIONES (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    CALLE VARCHAR (100) NOT NULL,
    NUMERO VARCHAR (100) NOT NULL,
    COLONIA VARCHAR (100) NOT NULL
);

CREATE TABLE CLIENTES (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR (100) NOT NULL,
    AP_PATERNO VARCHAR (100) NOT NULL,
    AP_MATERNO VARCHAR (100),
    CODIGO_DIRECCION INT NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    EDAD INT NOT NULL,
    FOREIGN KEY (CODIGO_DIRECCION) REFERENCES DIRECCIONES (CODIGO)
);

CREATE TABLE CUENTAS (
	NUM_CUENTA INT PRIMARY KEY,
    FECHA_APERTURA DATE NOT NULL,
    SALDO DECIMAL,
    CODIGO_CLIENTES INT NOT NULL,
    FOREIGN KEY (CODIGO_CLIENTES) REFERENCES CLIENTES (CODIGO)
);
    